recipe: default.v1
assistant_id: 20230707-094240-rust-drink
language: fr
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 10
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 200
  - name: RulePolicy

# language: "fr" 
# pipeline:
#   - name: LanguageModelFeaturizer
#     model_name: "bert"
#     model_weights: "rasa/LaBSE"
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 1000
#   - name: ResponseSelector
#     epochs: 1000
# policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
